AWSTemplateFormatVersion: 2010-09-09
Description: Template to provision a SageMaker Notebook and IAM role for Bedrock

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Required Parameters
        Parameters:
          - BedrockNotebookName
    ParameterLabels:      
      BedrockNotebookName:
        default: Name of SageMaker Notebook Instance
      
Parameters:
  BedrockNotebookName:
    Default: hello-bedrock
    Type: String
    Description: Enter name of SageMaker Notebook instance. The notebook name must _not_ already exist in your AWS account/region.
    MinLength: 1
    MaxLength: 63
    AllowedPattern: ^[a-z0-9](-*[a-z0-9])*
    ConstraintDescription: Must be lowercase or numbers with a length of 1-63 characters.
  BedrockIAMRole:
    Description: Name of IAM role that will be created by this cloud formation template. The role name must _not_ already exist in your AWS account.
    Type: String
    Default: "BedrockIAMRole"   

Resources:

  NotebookInstance:
    Type: AWS::SageMaker::NotebookInstance
    Properties:
      NotebookInstanceName: !Ref BedrockNotebookName
      InstanceType: ml.t3.xlarge
      RoleArn: !GetAtt NotebookRole.Arn

  NotebookRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref BedrockIAMRole
      Policies:
        - PolicyName: CustomNotebookAccess
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Sid: BedrockFullAccess
                Effect: Allow
                Action:
                  - "bedrock:*"
                Resource: "*"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSageMakerFullAccess
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/AWSCloudFormationReadOnlyAccess
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
              - sagemaker.amazonaws.com
            Action:
              - 'sts:AssumeRole'
          - Effect: Allow
            Principal:
              Service:
              - bedrock.amazonaws.com
            Action:
              - 'sts:AssumeRole'
Outputs:
  Region:
    Description: Deployed Region
    Value: !Ref AWS::Region
  BedrockNotebookURL:
    Description: Bedrock Notebook Instance
    Value: !Join
      - ''
      - - !Sub 'https://console.aws.amazon.com/sagemaker/home?region=${AWS::Region}#/notebook-instances/openNotebook/'
        - !GetAtt NotebookInstance.NotebookInstanceName
        - '?view=classic'
